// src/components/ItemCard.jsx
// ─────────────────────────────────────────────────────────────────
// Item Card — used in the Home Feed grid
// Fixes applied:
// - Real images from Unsplash with emoji fallback
// - Category colour coding
// - inference_ms display
// - Naija badge display
// ─────────────────────────────────────────────────────────────────

import {
  Box,
  Text,
  Badge,
  HStack,
  Button,
  VStack,
  Tooltip,
  Flex,
  useColorModeValue,
} from "@chakra-ui/react";
import { useNavigate } from "react-router-dom";

const CATEGORY_COLORS = {
  "Restaurant": "orange",
  "Book": "blue",
  "Music": "purple",
  "Movie": "red",
  "Product": "gray",
};
import { useApp } from "../context/AppContext";
import StarRating from "./StarRating";

export default function ItemCard({ item, review }) {
  const navigate    = useNavigate();
  const { isNaija } = useApp();

  const cardBg      = useColorModeValue("white", "#1E1E1E");
  const borderColor = useColorModeValue("gray.200", "gray.700");
  const reviewColor = useColorModeValue("gray.600", "gray.400");
  const metaColor   = useColorModeValue("gray.400", "gray.500");

  // Truncate review text to a short snippet
  function truncate(text, max = 85) {
    if (!text) return "";
    return text.length > max ? text.slice(0, max) + "…" : text;
  }

  // Adapter badge colour
  function adapterColor(adapter) {
    if (adapter === "user_adapter")       return "teal";
    if (adapter === "population_adapter") return "orange";
    return "gray";
  }

  const categoryColor = CATEGORY_COLORS[item.category] || "gray";

  return (
    <Box
      bg={cardBg}
      borderWidth="1px"
      borderColor={borderColor}
      borderRadius="xl"
      overflow="hidden"
      transition="all 0.2s"
      _hover={{
        shadow: "md",
        transform: "translateY(-3px)",
        borderColor: "brand.300",
      }}
      cursor="pointer"
      onClick={() => navigate(`/item/${item.id}`, { state: { item } })}
    >
      {/* ── Image area with Unsplash + emoji fallback ────────── */}
      <Flex
        h="110px"
        bg={`${categoryColor}.50`}
        align="center"
        justify="center"
        fontSize="3xl"
        borderBottom="1px solid"
        borderColor={borderColor}
        position="relative"
        overflow="hidden"
      >
        {/* Real image from Amazon dataset (or fallback) */}
        <img
          src={item.image || `https://source.unsplash.com/400x300/?${encodeURIComponent(item.imageQuery)}`}
          alt={item.title}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "cover",
            position: "absolute",
            top: 0,
            left: 0,
          }}
          onError={(e) => {
            e.target.style.display = "none";
          }}
        />
        {/* Emoji fallback — shows if image fails */}
        <Box position="relative" zIndex={1} fontSize="3xl">
          {item.emoji}
        </Box>
      </Flex>

      {/* ── Card body ───────────────────────────────────────── */}
      <VStack align="stretch" p={4} spacing={2}>

        {/* Category badge + adapter badge + Naija badge */}
        <HStack justify="space-between" align="center" wrap="wrap" gap={1}>
          <Badge
            colorScheme={categoryColor}
            fontSize="10px"
            px={2}
            py={0.5}
            borderRadius="full"
          >
            {item.category}
          </Badge>

          <HStack spacing={1}>
            {/* Twin badge — always shown since it's always the personal twin */}
            {review && (
              <Tooltip
                label="Generated by your Digital Twin"
                placement="top"
                hasArrow
                fontSize="xs"
              >
                <Badge
                  colorScheme="teal"
                  fontSize="9px"
                  px={2}
                  borderRadius="full"
                  cursor="help"
                >
                  Personal Twin
                </Badge>
              </Tooltip>
            )}

            {/* Naija badge — always shown when Naija mode is ON */}
            {isNaija && (
              <Badge
                colorScheme="orange"
                fontSize="9px"
                px={2}
                borderRadius="full"
              >
                🇳🇬 Naija
              </Badge>
            )}
          </HStack>
        </HStack>

        {/* Item title & Price */}
        <HStack justify="space-between" align="start">
          <Text fontWeight="600" fontSize="sm" lineHeight="1.3" noOfLines={1} title={item.title}>
            {item.title}
          </Text>
          {item.price && (
            <Badge colorScheme="green" variant="subtle" fontSize="xs" whiteSpace="nowrap">
              ${item.price.toFixed(2)}
            </Badge>
          )}
        </HStack>

        {/* Star rating — uses predicted_rating from real API */}
        {review ? (
          <StarRating rating={review.predicted_rating} size="sm" />
        ) : (
          <StarRating rating={0} size="sm" />
        )}

        {/* Review snippet */}
        <Tooltip
          label="Generated by your personal AI twin"
          placement="top"
          hasArrow
          fontSize="xs"
        >
          <Text
            fontSize="xs"
            color={reviewColor}
            noOfLines={2}
            lineHeight="1.5"
            fontStyle="italic"
          >
            {review
              ? `"${truncate(review.review)}"`
              : "Generating review…"}
          </Text>
        </Tooltip>

        {/* Confidence score from real API */}
        {review && (
          <Text fontSize="9px" color={metaColor}>
            Confidence: {((review.confidence ?? 0) * 100).toFixed(0)}% · Personal Twin
          </Text>
        )}

        {/* Action buttons */}
        <HStack spacing={2} pt={1}>
          <Button
            size="xs"
            colorScheme={categoryColor}
            variant="outline"
            borderRadius="md"
            onClick={(e) => {
              e.stopPropagation();
              navigate(`/item/${item.id}`, { state: { item } });
            }}
          >
            Full review
          </Button>
          <Button
            size="xs"
            variant="ghost"
            color="gray.500"
            borderRadius="md"
            onClick={(e) => {
              e.stopPropagation();
              navigate(
                `/chat?item=${item.id}&title=${encodeURIComponent(item.title)}`
              );
            }}
          >
             Chat
          </Button>
        </HStack>

      </VStack>
    </Box>
  );
}